package menus;

import java.util.Scanner;

import beans.Account;
import beans.User;
import dao.AccountDimple;
import dao.Transaction;

public class MainMenu {
	static Scanner sc;
	static String[] optionsArray = { "1. I am a customer", "2. I am an employee", "3. I am an admin", "4. Return to login menu." };
	
	public void firstLoginMenu() {
//		Dummies.addDummies();
		Transaction t = new Transaction();
		t.insertAdmins();
		sc = new Scanner(System.in);
		boolean flag = true;
		System.out.println("Welcome to Stacks of Cache Bank.");
		System.out.println("Please sign up or login.");
		System.out.println("1. Sign up.\n2. Sign in.");
		while (flag) {

			String newUser = sc.nextLine();
			switch (newUser) {
			case "1":
				createNewUser();
				flag = !flag;
				break;
			case "2":
				mainMenu();
				flag = !flag;
				break;
			default:
				firstLoginMenu();
				flag = !flag;
				break;
			}
		}
	}

	public void mainMenu() {
		System.out.println("Main Menu");
		for (String s : optionsArray) {
			System.out.println(s);
		}
		System.out.println("Please select an option to continue");
		String choice = sc.nextLine();
		loginHandler(choice);
	}

	public void loginHandler(String choice) {
		UtilityMenus utilMenu = new UtilityMenus();

		boolean flag = true;
		while (flag) {

			switch (choice) {
			case "1":
//				CustomerMenu.loginMenu();
				CustomerMenu custMenu = new CustomerMenu();
				custMenu.loginMenu();
				flag = !flag;
				break;
			case "2":
//				ApprovedAccounts.employeeLogin();
				EmployeeMenu empMenu = new EmployeeMenu();
				empMenu.loginMenu();
				flag = !flag;
				break;
			case "3":
//				ApprovedAccounts.adminLogin();
				AdminMenu adminMenu = new AdminMenu();
				adminMenu.loginMenu();
				flag = !flag;
				break;
			case "4":
				firstLoginMenu();
			default:
				System.out.println("Select a choice.");
				mainMenu();
				flag = !flag;
				break;
			}
		}
	}

	public Account createNewUser() {
//		AccountDimple adi = new AccountDimple();
		User newUser = null;
		String newAID;
		Transaction t = new Transaction();
		sc = new Scanner(System.in);
		Account newAccount = null;
		System.out.println("Enter a username.");
		try { String username = sc.nextLine();
		System.out.println("Enter a password.");
		String pw = sc.nextLine();
		System.out.println("Enter a balance");
		Double balance = sc.nextDouble();
		sc = new Scanner(System.in);
		System.out.println("Please enter a word to act as your temporary security token.");
		String token = sc.nextLine();
		System.out.println("Joint account? 1 for yes, 2 for no.");
		String joint = sc.nextLine();
		newUser = new User(username, pw);
		switch (joint) {
		case "1":
			System.out.println("Enter a second username");
			String jointUsername = sc.nextLine();
			System.out.println("Password for joint holder.");
			String passw = sc.nextLine();
			System.out.println("Wait a moment while we create your account.");
			User jointUser = new User(jointUsername, passw);
			t.createUser(newUser); // insert users into user table.
			t.createUser(jointUser);
			newAccount = new Account(null,balance, 0, token);
			t.createAccount(newAccount); // insert account into accounts table
			newAID = t.findAIDByToken(token); // retrieve AID that was automatically generated by the insertion trigger for accounts table
			t.insertIntoJunction(newUser.getUsername(), newAID); // insert both users into the junction table with the same AID
			t.insertIntoJunction(jointUser.getUsername(), newAID);
			t.eraseTempToken(newAID); // erase the token to avoid having two primary keys.
			break;
		case "2":
			System.out.println("Wait one moment while we create your user profile and account.");
			newAccount = new Account(null,balance, 0, token);
			newUser = new User(username, pw);
//			Transaction t = new Transaction(); // add user to user table
			t.createUser(newUser); // add user to db
			t.createAccount(newAccount); // adds account to DB, where it gets an AID...
			// method to retrieve AID by token.
			newAID = t.findAIDByToken(token);
			t.insertIntoJunction(newUser.getUsername(),newAID);
			t.eraseTempToken(newAID);
			mainMenu();
			break;
		}
		mainMenu();
		} 
		catch(Exception e) {
			System.out.println("Invalid input");
			firstLoginMenu();
		}
//		t.createUser(newUser);
//		t.createAccount(newAccount);
		

//		firstLoginMenu();
		return newAccount;
	}
}
